# Generated by Django 5.1.15 on 2026-05-29 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conceptos', '0002_initial'),
        ('lecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leccionconcepto',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conceptos.concepto'),
        ),
        migrations.AddField(
            model_name='leccionconcepto',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecciones.leccion'),
        ),
        migrations.AddField(
            model_name='leccion',
            name='conceptos',
            field=models.ManyToManyField(related_name='lecciones', through='lecciones.LeccionConcepto', to='conceptos.concepto'),
        ),
        migrations.AlterUniqueTogether(
            name='leccionconcepto',
            unique_together={('leccion', 'concepto')},
        ),
    ]
