# Generated by Django 5.1.15 on 2026-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_ingles', models.CharField(max_length=120)),
                ('transcripcion_fonetica', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('audio', models.FileField(upload_to='audios/')),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['palabra_ingles'],
            },
        ),
    ]
