# Generated by Django 5.1.15 on 2026-06-05 21:09

import apps.conceptos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='audio',
            field=models.FileField(upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg']), apps.conceptos.validators.TamanoMaximoArchivo(10)]),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.conceptos.validators.TamanoMaximoArchivo(5)]),
        ),
    ]
