# Generated by Django 5.1.15 on 2026-06-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizes'},
        ),
    ]
